### ISSUE TITLE
config.json识别不出

### ISSUE THREAD

**Issue by zyp123456789** [abrahum/nonebot_plugin_simdraw#1]
我按照文档的内容给bot.py所在路径提供了cache/simdraw文件夹内也包含了config.json文件 ,可是nonebot无法找到config.json文件，根据代码，我把cachepath = 换成绝对路径（不包含config.json）也没用，希望可以得到大佬解决。
![5N7(RLKX1S%Y)2JCS))H )G](https://user-images.githubusercontent.com/27912639/105863525-f0846200-602b-11eb-8db7-3322579d3f5a.png)

按照原配置填写任然找不到config.json文件。
![}B5G61F(14P9K~@Q~5{OURM](https://user-images.githubusercontent.com/27912639/105863727-26c1e180-602c-11eb-9514-0ee00e43febd.png)
![U%H8LTII{(94A468`LLX0 M](https://user-images.githubusercontent.com/27912639/105863857-478a3700-602c-11eb-9cca-92577e19c0e3.png)

这是我的bot目录
![OSY(4)9B_N9_XB~V79K6L0X](https://user-images.githubusercontent.com/27912639/105864033-799b9900-602c-11eb-939e-65760379fd29.png)

**Comment by abrahum** [comment]
cache夹和bot.py是同级的，你是不是吧cache文件夹建在和plugins文件夹同级了

**Comment by liwh011** [comment]
我也遇到这个问题。打开data_source.py，把71行的exception给显示出来，会发现并不是`FileNotFoundError`，而是`UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 112: illegal multibyte sequence`

出现这个的原因是：win10中文下，读取文件时默认文件编码是gbk。这样就造成了无法解析utf8编码的文件的问题。我在linux服务器上操作，并不会出现这个问题。

因此，把data_source.py的第67行加上`encoding="utf-8"`，即改为`with open(os.path.join(cachepath, "config.json"), "r", encoding="utf-8") as f:`，就可以在win下正常运行了。

**Comment by zyp123456789** [comment]
> 我也遇到这个问题。打开data_source.py，把71行的exception给显示出来，会发现并不是，而是`FileNotFoundError``UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 112: illegal multibyte sequence`
> 
> 出现这个的原因是：win10中文下，读取文件时默认文件编码是gbk。这样就造成了无法解析utf8编码的文件的问题。我在linux服务器上操作，并不会出现这个问题。
> 
> 因此，把data_source.py的第67行加上，即改为，就可以在win下正常运行了。`encoding="utf-8"``with open(os.path.join(cachepath, "config.json"), "r", encoding="utf-8") as f:`

感谢大佬，已经解决❤❤❤

**Comment by abrahum** [comment]
一直是在linux写的这个插件，确实忘了这个适配，已修复，感谢反馈~
